### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ghost** [vahuynh/GENIE3#1]
Hello，
I recently read a paper from you， **Inferring Regulatory Networks from Expression Data
Using Tree-Based Methods**， but I have a trouble， if we have calculated weights,  how choose an  appropriate  threshold  to get  the relationships between genes.
 
Thank you for you time.

**Comment by vahuynh** [comment]
GENIE3 only provides a ranking of the network edges and not a network topology. The weights returned by GENIE3 are not statistically interpretable and thus choosing an appropriate threshold remains an open problem so far.
