### ISSUE TITLE
Issue with running GENIE3 with its default parameters

### ISSUE THREAD

**Issue by sktowusuansah** [vahuynh/GENIE3#11]
Hello Van Anh,

Following through the basic implementation in R using the GENIE3 documentation provided, I get stuck anytime I attempt to run GENIE3 with its default parameters. In the quest to compute the weighted adjacency matrix of the gene network with the GENIE3 algorithm, I input the following line of code:

 weight.matrix1 <- GENIE3(expr.matrix)

The resulting error output is shown below:

Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/DELL PC/Desktop/CU/Academic Files/Research/Genie3/GENIE3.so':
  LoadLibrary failure:  The specified module could not be found.
Called from: inDL(x, as.logical(local), as.logical(now), ...)
Browse[1]> 

It appears the package requires a GENIE3.so file to run but that module could not be found. I have tried a plethora of approaches to fix the issue but none have given me any positive result. I am unsure what to do next.

I would appreciate if you could recommend a way to get around this. Thank you.

**Comment by vahuynh** [comment]
Hi,

You must first compile the C code by typing the following command:
`R CMD SHLIB GENIE3.c`
This will create the GENIE3.so file that you need.

Another (and probably easier) option is to install the GENIE3 library from Bioconductor:
https://bioconductor.org/packages/release/bioc/html/GENIE3.html

I hope it helps.

Vân Anh
