### ISSUE TITLE
Doubt on variance importance and (multi)collinearity

### ISSUE THREAD

**Issue by MiqG** [vahuynh/GENIE3#4]
Hi!

First, thank you for developing such a cool new concept for network inference in the omics!

After reading your [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0012776), I was wondering whether the variable importances obtained could be confounded by having multicollinearity between genes like is explained [here](https://scikit-learn.org/stable/auto_examples/inspection/plot_permutation_importance_multicollinear.html#sphx-glr-auto-examples-inspection-plot-permutation-importance-multicollinear-py). 
Then, I understand that highly collinear features (genes) will be used for splitting observations close to the root a few times for each tree because they hold very similar information with respect to the target variable. And, therefore, these will have low importance when averaging over all the ensemble.
Is this true with the current implementation of variable importance?

Thank you very much again!

Miquel

**Comment by vahuynh** [comment]
Hi Miquel,

Yes, this is an issue that you can have with the current implementation of variable importance.
When several input genes are highly correlated, the information that they bring about the target gene will tend to spread across them, resulting in lower importance scores.

I have however never tried to correct this issue in the context of network inference.
