### ISSUE TITLE
Error importing GENIE3

### ISSUE THREAD

**Issue by mayank1729** [vahuynh/GENIE3#5]
Despite installing the latest version of the scikit-learn library, upon executing `from GENIE3 import *` 
I am getting the error - " No module named 'GENIE3' ".

(Getting the error while following the python documentation of GENIE3)

Have tried it on spyder, jupyter notebook and google colab.

**Comment by vahuynh** [comment]
Hi,

Actually, GENIE3 is not provided within the scikit-learn library.
To be able to import GENIE3, the GENIE3.py file should be in your working directory.
