### ISSUE TITLE
The application of GENIE3 to pathway score matrix

### ISSUE THREAD

**Issue by DrZhaoJie** [vahuynh/GENIE3#7]
Hi, I really enjoy your package GENIE3. I had an idea. May I apply the method to a pathway score matrix (calculated from GSVA)  to find the co-interaction of the pathways? And then find hub-pathway by Cytoscape? 
Was this reasonable? Thank you very much!

**Comment by vahuynh** [comment]
Hi,

Well, if you think that it makes sense to try to predict the score of a pathway from the scores of other pathways, then yes you can use GENIE3 to identify the interactions between pathways. GENIE3 is very generic, and hence can potentially be used to find interactions between nodes of a graph, whatever the type of the nodes.

Best,
Vân Anh
